# Generated by Django 3.2.5 on 2022-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_room',
            name='online',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
